name: Test Toolchains

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  test-toolchains:
    name: Test Toolchains (MSVC, Clang, MinGW)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup Xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Cache Xmake packages
        uses: actions/cache@v6
        with:
          path: |
            ~/.xmake
            build/.gens
          key: ${{ runner.os }}-xmake-test-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            ${{ runner.os }}-xmake-test-

      - name: Test MSVC
        run: |
          xmake f -p windows -a x86 -m release --toolchain=msvc -y -v
          xmake -v
          xmake clean --all

      - name: Test Clang
        run: |
          xmake f -p windows -a x86 -m release --toolchain=clang --runtimes=MT -y -v
          xmake -v
          xmake clean --all

      # WAIT FOR GCC16
      # - name: Test MinGW
      #   run: |
      #     xmake g --mingw="C:/mingw32"
      #     xmake f -p windows -a x86 -m release --toolchain=mingw --mingw=C:/mingw32 -y -v
      #     xmake -v
